name: fitness_app
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter

  pedometer: ^4.1.0

  flutter_swiper: ^1.2.0

  bmi_calculator: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

environment:
  sdk: ">=2.12.0 <3.0.0"
