name: your_project_name
description: A new Flutter project

dependencies:
 flutter:
  sdk: flutter
 location: ^5.0.3
 geolocator: ^10.1.0
 fl_chart: ^0.64.0

environment:
 sdk: ">=2.12.0 <3.0.0" # Check and adjust the Dart SDK version here.

